-- MySQL Script generated by MySQL Workbench
-- Thu Nov  1 19:58:09 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema OAE
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OAE
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OAE` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `OAE` ;

-- -----------------------------------------------------
-- Table `OAE`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OAE`.`event` (
  `id_event` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `place` VARCHAR(600) NULL,
  `time` VARCHAR(20) NULL,
  PRIMARY KEY (`id_event`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `OAE`.`institute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OAE`.`institute` (
  `id` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `id_event` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `institute_event_idx` (`id_event` ASC),
  CONSTRAINT `institute_event`
    FOREIGN KEY (`id_event`)
    REFERENCES `OAE`.`event` (`id_event`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `OAE`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OAE`.`user` (
  `username` INT NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `job` VARCHAR(60) NOT NULL,
  `id_institute` INT NOT NULL,
  PRIMARY KEY (`username`),
  INDEX `user_institute_idx` (`id_institute` ASC),
  CONSTRAINT `user_institute`
    FOREIGN KEY (`id_institute`)
    REFERENCES `OAE`.`institute` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `OAE`.`school`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OAE`.`school` (
  `name` VARCHAR(100) NOT NULL,
  `level` VARCHAR(20) NOT NULL,
  `id_institute` INT NOT NULL,
  PRIMARY KEY (`name`),
  INDEX `institute_school_idx` (`id_institute` ASC),
  CONSTRAINT `institute_school`
    FOREIGN KEY (`id_institute`)
    REFERENCES `OAE`.`institute` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `OAE`.`guest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OAE`.`guest` (
  `rfc` VARCHAR(10) NOT NULL,
  `number` INT NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `middleName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `seat` INT NULL,
  `email` VARCHAR(45) NULL,
  `assistance` TINYINT NULL,
  `representative` VARCHAR(100) NULL,
  `type` VARCHAR(45) NULL,
  `school` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`rfc`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `representative_UNIQUE` (`representative` ASC),
  INDEX `guest_school_idx` (`school` ASC),
  CONSTRAINT `guest_school`
    FOREIGN KEY (`school`)
    REFERENCES `OAE`.`school` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `OAE`.`prize`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OAE`.`prize` (
  `id_prize` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `block` INT NOT NULL,
  `speech` VARCHAR(1000) NOT NULL,
  `amount` INT NOT NULL,
  `id_event` INT NOT NULL,
  PRIMARY KEY (`id_prize`),
  INDEX `event_prize_idx` (`id_event` ASC),
  CONSTRAINT `event_prize`
    FOREIGN KEY (`id_event`)
    REFERENCES `OAE`.`event` (`id_event`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `OAE`.`guest_prize`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OAE`.`guest_prize` (
  `rfc` VARCHAR(10) NOT NULL,
  `id_prize` INT NOT NULL,
  PRIMARY KEY (`rfc`, `id_prize`),
  INDEX `gp_prize_idx` (`id_prize` ASC),
  CONSTRAINT `gp_guest`
    FOREIGN KEY (`rfc`)
    REFERENCES `OAE`.`guest` (`rfc`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `gp_prize`
    FOREIGN KEY (`id_prize`)
    REFERENCES `OAE`.`prize` (`id_prize`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `OAE`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OAE`.`comment` (
  `comment` VARCHAR(1000) NOT NULL,
  `rfc` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`comment`, `rfc`),
  INDEX `comment_guest_idx` (`rfc` ASC),
  CONSTRAINT `comment_guest`
    FOREIGN KEY (`rfc`)
    REFERENCES `OAE`.`guest` (`rfc`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `OAE`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OAE`.`news` (
  `news` VARCHAR(1000) NOT NULL,
  `id_event` INT NOT NULL,
  PRIMARY KEY (`news`, `id_event`),
  INDEX `news_event_idx` (`id_event` ASC),
  CONSTRAINT `news_event`
    FOREIGN KEY (`id_event`)
    REFERENCES `OAE`.`event` (`id_event`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
