-- MySQL Script generated by MySQL Workbench
-- Fri Nov 16 18:15:57 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema OrganizeAnEvent
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OrganizeAnEvent
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OrganizeAnEvent` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `OrganizeAnEvent`;

-- -----------------------------------------------------
-- Table `OrganizeAnEvent`.`Institution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OrganizeAnEvent`.`Institution` (
  `InstitutionID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`InstitutionID`))
ENGINE = InnoDB;

SHOW WARNINGS;


-- -----------------------------------------------------
-- Table `OrganizeAnEvent`.`Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OrganizeAnEvent`.`Event` (
  `EventID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `Localization` VARCHAR(600) NULL,
  `Latitude` DOUBLE NULL,
  `Longitude` DOUBLE NULL,
  `Time` DATETIME NULL,
  `Description` VARCHAR(1000) NULL,
  `InstitutionID` INT,
  PRIMARY KEY (`EventID`),
  INDEX `event_institution_idx` (`InstitutionID` ASC),
  CONSTRAINT `EventInstitution`
    FOREIGN KEY (`InstitutionID`)
    REFERENCES `OrganizeAnEvent`.`Institution` (`InstitutionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;


-- -----------------------------------------------------
-- Table `OrganizeAnEvent`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OrganizeAnEvent`.`User` (
  `Username` INT NOT NULL,
  `Password` VARCHAR(256) NOT NULL,
  `Type` ENUM('Admin', 'Standard') NOT NULL)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `OrganizeAnEvent`.`UserEvent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OrganizeAnEvent`.`UserEvent` (
  `Username` INT NOT NULL,
  `EventID` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`Username`, `EventID`),
  INDEX `userevent_username_idx` (`Username` ASC),
  CONSTRAINT `UserEventUsername`
    FOREIGN KEY (`Username`)
    REFERENCES `OrganizeAnEvent`.`User` (`Username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
  INDEX `userevent_eventid_idx` (`EventID` ASC),
  CONSTRAINT `UserEventEventID`
    FOREIGN KEY (`EventID`)
    REFERENCES `OrganizeAnEvent`.`Event` (`EventID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `OrganizeAnEvent`.`Place`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OrganizeAnEvent`.`Place` (
  `PlaceID` VARCHAR(6) NOT NULL,
  `Name` VARCHAR(100) NOT NULL,
  `Level` VARCHAR(20) NOT NULL,
  `InstitutionID` INT NOT NULL,
  INDEX `institution_place_idx` (`InstitutionID` ASC),
  PRIMARY KEY (`PlaceID`),
  CONSTRAINT `InstitutionPlace`
    FOREIGN KEY (`InstitutionID`)
    REFERENCES `OrganizeAnEvent`.`Institution` (`InstitutionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `OrganizeAnEvent`.`Guest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OrganizeAnEvent`.`Guest` (
  `RFC` VARCHAR(10) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `FirstSurname` VARCHAR(45) NOT NULL,
  `SecondSurname` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NULL,
  `PlaceID` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`RFC`),
  INDEX `guest_place_idx` (`PlaceID` ASC),
  CONSTRAINT `GuestPlace`
    FOREIGN KEY (`PlaceID`)
    REFERENCES `OrganizeAnEvent`.`Place` (`PlaceID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `OrganizeAnEvent`.`Prize`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OrganizeAnEvent`.`Prize` (
  `PrizeID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `Block` INT NOT NULL,
  `Speech` VARCHAR(1000) NOT NULL,
  `Amount` INT NOT NULL,
  `EventID` INT NOT NULL,
  PRIMARY KEY (`PrizeID`),
  INDEX `event_prize_idx` (`EventID` ASC),
  CONSTRAINT `EventPrize`
    FOREIGN KEY (`EventID`)
    REFERENCES `OrganizeAnEvent`.`Event` (`EventID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `OrganizeAnEvent`.`GuestPrize`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OrganizeAnEvent`.`GuestPrize` (
  `RFC` VARCHAR(10) NOT NULL,
  `PrizeID` INT NOT NULL,
  PRIMARY KEY (`PrizeID`, `RFC`),
  INDEX `gp_prize_idx` (`PrizeID` ASC),
  CONSTRAINT `GPGuest`
    FOREIGN KEY (`RFC`)
    REFERENCES `OrganizeAnEvent`.`Guest` (`RFC`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `GPPrize`
    FOREIGN KEY (`PrizeID`)
    REFERENCES `OrganizeAnEvent`.`Prize` (`PrizeID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `OrganizeAnEvent`.`GuestEvent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OrganizeAnEvent`.`GuestEvent` (
  `RFC` VARCHAR(10) NOT NULL,
  `EventID` INT NOT NULL,
  `Number` INT NULL,
  `Confirmation` TINYINT(1) NULL,
  `Assistance` TINYINT(1) NULL,
  `Seat` INT NULL,
  `Representative` VARCHAR(100) NULL,
  PRIMARY KEY (`RFC`, `EventID`),
  INDEX `GEEvent_idx` (`EventID` ASC),
  CONSTRAINT `GEEvent`
    FOREIGN KEY (`EventID`)
    REFERENCES `OrganizeAnEvent`.`Event` (`EventID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `GEGuest`
    FOREIGN KEY (`RFC`)
    REFERENCES `OrganizeAnEvent`.`Guest` (`RFC`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `OrganizeAnEvent`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OrganizeAnEvent`.`Comment` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Text` VARCHAR(1000) NULL,
  `RFC` VARCHAR(10) NOT NULL,
  `EventID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `comment_guest_idx` (`RFC` ASC),
  CONSTRAINT `CommentGuest`
    FOREIGN KEY (`RFC`)
    REFERENCES `OrganizeAnEvent`.`Guest` (`RFC`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  INDEX `comment_event_idx` (`EventID` ASC),
  CONSTRAINT `CommentEvent`
    FOREIGN KEY (`EventID`)
    REFERENCES `OrganizeAnEvent`.`Event` (`EventID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `OrganizeAnEvent`.`News`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OrganizeAnEvent`.`News` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Text` VARCHAR(1000) NULL,
  `EventID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `news_event_idx` (`EventID` ASC),
  CONSTRAINT `NewsEvent`
    FOREIGN KEY (`EventID`)
    REFERENCES `OrganizeAnEvent`.`Event` (`EventID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
