-- MySQL Script generated by MySQL Workbench
-- Fri Nov 16 18:15:57 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema OAE
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OAE
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OAE` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `OAE` ;

-- -----------------------------------------------------
-- Table `OAE`.`Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OAE`.`Event` (
  `EventID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `Localization` VARCHAR(600) NULL,
  `Latitude` DOUBLE NULL,
  `Longitude` DOUBLE NULL,
  `Time` DATETIME NULL,
  `Description` VARCHAR(1000) NULL,
  PRIMARY KEY (`EventID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `OAE`.`Institution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OAE`.`Institution` (
  `InstitutionID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(50) NOT NULL,
  `EventID` INT NULL,
  PRIMARY KEY (`InstitutionID`),
  INDEX `institution_event_idx` (`EventID` ASC),
  CONSTRAINT `InstitutionEvent`
    FOREIGN KEY (`EventID`)
    REFERENCES `OAE`.`Event` (`EventID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `OAE`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OAE`.`User` (
  `Username` INT NOT NULL,
  `Password` VARCHAR(256) NOT NULL,
  `Type` ENUM('Admin', 'Standard') NOT NULL,
  `InstitutionID` INT NOT NULL,
  PRIMARY KEY (`Username`),
  INDEX `user_institution_idx` (`InstitutionID` ASC),
  CONSTRAINT `UserInstitution`
    FOREIGN KEY (`InstitutionID`)
    REFERENCES `OAE`.`Institution` (`InstitutionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `OAE`.`Place`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OAE`.`Place` (
  `PlaceID` VARCHAR(6) NOT NULL,
  `Name` VARCHAR(100) NOT NULL,
  `Level` VARCHAR(20) NOT NULL,
  `InstitutionID` INT NOT NULL,
  INDEX `institution_place_idx` (`InstitutionID` ASC),
  PRIMARY KEY (`PlaceID`),
  CONSTRAINT `InstitutionPlace`
    FOREIGN KEY (`InstitutionID`)
    REFERENCES `OAE`.`Institution` (`InstitutionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `OAE`.`Guest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OAE`.`Guest` (
  `RFC` VARCHAR(10) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `FirstSurname` VARCHAR(45) NOT NULL,
  `SecondSurname` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NULL,
  `PlaceID` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`RFC`),
  INDEX `guest_place_idx` (`PlaceID` ASC),
  CONSTRAINT `GuestPlace`
    FOREIGN KEY (`PlaceID`)
    REFERENCES `OAE`.`Place` (`PlaceID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `OAE`.`Prize`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OAE`.`Prize` (
  `PrizeID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `Block` INT NOT NULL,
  `Speech` VARCHAR(1000) NOT NULL,
  `Amount` INT NOT NULL,
  `EventID` INT NOT NULL,
  PRIMARY KEY (`PrizeID`),
  INDEX `event_prize_idx` (`EventID` ASC),
  CONSTRAINT `EventPrize`
    FOREIGN KEY (`EventID`)
    REFERENCES `OAE`.`Event` (`EventID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `OAE`.`GuestPrize`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OAE`.`GuestPrize` (
  `RFC` VARCHAR(10) NOT NULL,
  `PrizeID` INT NOT NULL,
  PRIMARY KEY (`PrizeID`, `RFC`),
  INDEX `gp_prize_idx` (`PrizeID` ASC),
  CONSTRAINT `GPGuest`
    FOREIGN KEY (`RFC`)
    REFERENCES `OAE`.`Guest` (`RFC`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `GPPrize`
    FOREIGN KEY (`PrizeID`)
    REFERENCES `OAE`.`Prize` (`PrizeID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `OAE`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OAE`.`Comment` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Text` VARCHAR(1000) NULL,
  `RFC` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `comment_guest_idx` (`RFC` ASC),
  CONSTRAINT `CommentGuest`
    FOREIGN KEY (`RFC`)
    REFERENCES `OAE`.`Guest` (`RFC`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `OAE`.`News`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OAE`.`News` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Text` VARCHAR(1000) NULL,
  `EventID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `news_event_idx` (`EventID` ASC),
  CONSTRAINT `NewsEvent`
    FOREIGN KEY (`EventID`)
    REFERENCES `OAE`.`Event` (`EventID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `OAE`.`GuestEvent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OAE`.`GuestEvent` (
  `RFC` VARCHAR(10) NOT NULL,
  `EventID` INT NOT NULL,
  `Number` INT NULL,
  `Confirmation` TINYINT NULL,
  `Assistance` TINYINT NULL,
  `Seat` INT NULL,
  `Representative` VARCHAR(100) NULL,
  PRIMARY KEY (`RFC`, `EventID`),
  INDEX `GEEvent_idx` (`EventID` ASC),
  CONSTRAINT `GEEvent`
    FOREIGN KEY (`EventID`)
    REFERENCES `OAE`.`Event` (`EventID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `GEGuest`
    FOREIGN KEY (`RFC`)
    REFERENCES `OAE`.`Guest` (`RFC`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
